plugins {
    id 'java'
    id 'application'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'ua.store.Main'
}

// tasks.withType(JavaCompile).configureEach {
//     options.encoding = 'UTF-8'
// }

// tasks.withType(JavaExec).configureEach {
//     defaultCharacterEncoding = 'UTF-8'
// }
// WRITE IN TERMINAL B4 RUN 65001; [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
tasks.withType(JavaExec).configureEach {
    defaultCharacterEncoding = 'UTF-8'
    jvmArgs '-Dfile.encoding=UTF-8', '-Dsun.stdout.encoding=UTF-8', '-Dsun.stderr.encoding=UTF-8'
}